ACTION_CAPTURE.capturableBuildings = ["AIRPORT", "FACTORY", "HARBOUR", "HQ", "LABOR", "MINE",
    "PIPESTATION", "RADAR", "TOWER", "TOWN", "TEMPORARY_AIRPORT",
    "TEMPORARY_HARBOUR", "OILRIG", "POWERPLANT", "AMPHIBIOUSFACTORY",
    "FIELD_BASE","BUILDSITE"]